email_password          = "wurwdsruvsvccivo"
email_receiver          = "orid@kikero.app"
email_sender            = "fiiletype.update@gmail.com"
s3_bucket_name          = "s3-filetype-trigger"
lambda_function_name    = "terraform-lambda-01"
