name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        run: |
          echo "Build python image"
          docker build -t filetypeupdate:0.1.0 .
      - name: Update Lambda Function
        run: echo "Done, bye!"
