name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "First action"
          echo "Second action"
      - name: Print goodbye
        run: echo "Done, bye!"
