name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Build Docker Image
        working-directory: filetype
        run: |
          echo "Build python image"
          # docker build -t filetypeupdate:0.1.0 .
          ls -la 
          pwd
      - name: Update Lambda Function
        run: echo "Done, bye!"
