name: Second Workflow
on:
  push:
    branches: 
      - main 
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          
      - name: Setrup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5
